# Generated by Django 4.1.5 on 2023-01-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pelanggaran', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.IntegerField()),
                ('nama_siswa', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggaran.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='pelanggar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('pelanggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggaran.pelanggaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggaran.siswa')),
            ],
        ),
    ]
