# Generated by Django 4.1.5 on 2023-02-03 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pelanggaran', '0006_alter_pelanggar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
