# Generated by Django 4.1.5 on 2023-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaran', '0007_alter_pelanggar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
